---


- name: Configure Kernel for Kubernetes
  hosts: masters,workers
  become: yes
  tasks:
    - name: Disable swap immediately
      command: swapoff -a

    - name: Remove swap from fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*\sswap\s.*)$'
        replace: '# \1'

    - name: Load kernel modules
      modprobe:
        name: "{{ item }}"
      loop:
        - overlay
        - br_netfilter

    - name: Make kernel modules persistent
      copy:
        content: |
          # Kubernetes required modules
          overlay
          br_netfilter
        dest: /etc/modules-load.d/k8s.conf

    - name: Configure sysctl parameters
      copy:
        content: |
          # Kubernetes networking
          net.bridge.bridge-nf-call-iptables = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward = 1
          net.ipv4.conf.all.forwarding = 1
        dest: /etc/sysctl.d/k8s.conf

    - name: Apply sysctl settings
      command: sysctl --system

    - debug:
        msg: "✅ Kernel configured for Kubernetes on {{ inventory_hostname }}"