apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read-only-user
rules:
- apiGroups:
  - ""
  - apps
  - batch
  - networking.k8s.io
  verbs:
  - get
  - list
  - watch
  resources:
  - pods
  - services
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  - jobs
  - cronjobs
  - ingresses
  - configmaps
  - secrets
  - namespaces
  - nodes
