---


- name: Configure Kubernetes
  hosts: masters,workers
  become: yes
  vars_files:
    - ../../vars.yml
  tasks:
    - name: Configure kubelet
      copy:
        content: |
          KUBELET_EXTRA_ARGS="--cgroup-driver=systemd --container-runtime-endpoint=unix:///run/containerd/containerd.sock"
        dest: /etc/default/kubelet

    - name: Enable kubelet service
      systemd:
        name: kubelet
        enabled: yes
        daemon_reload: yes

    - debug:
        msg: "✅ Kubernetes configured on {{ inventory_hostname }}"