---

- name: Join Additional Masters
  hosts: master2,master3
  become: yes
  serial: 1  # Join one master at a time
  vars_files:
    - ../../vars.yml
  tasks:
    - name: Check if already joined to cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Generate fresh certificate key (expires in 2 hours)
      shell: kubeadm init phase upload-certs --upload-certs | tail -1
      register: cert_key
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true
      when: not kubelet_conf.stat.exists

    - name: Generate fresh join command
      shell: kubeadm token create --print-join-command
      register: join_command
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true
      when: not kubelet_conf.stat.exists

    - name: Create master join command
      set_fact:
        master_join_cmd: "{{ join_command.stdout }} --control-plane --certificate-key {{ cert_key.stdout }}"
      when: not kubelet_conf.stat.exists

    - name: Join master to cluster
      shell: "{{ master_join_cmd }}"
      when: not kubelet_conf.stat.exists

    - name: Setup kubectl for root
      shell: |
        mkdir -p /root/.kube
        cp /etc/kubernetes/admin.conf /root/.kube/config
        chown root:root /root/.kube/config
      when: not kubelet_conf.stat.exists

    - name: Setup kubectl for ansible user
      shell: |
        mkdir -p /home/ansible/.kube
        cp /etc/kubernetes/admin.conf /home/ansible/.kube/config
        chown ansible:ansible /home/ansible/.kube/config
      when: not kubelet_conf.stat.exists